set_property OUTPUT_VALUE 0 [get_hw_probes jesd204c_test_bd_i/control/vio_0_probe_out3 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
commit_hw_vio [get_hw_probes {jesd204c_test_bd_i/control/vio_0_probe_out3} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
after 100
set_property OUTPUT_VALUE 1 [get_hw_probes jesd204c_test_bd_i/control/vio_0_probe_out3 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
commit_hw_vio [get_hw_probes {jesd204c_test_bd_i/control/vio_0_probe_out3} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
after 3000 

set_property OUTPUT_VALUE 2000000800000001 [get_hw_probes jesd204c_test_bd_i/control/vio_0_probe_out12 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
commit_hw_vio [get_hw_probes {jesd204c_test_bd_i/control/vio_0_probe_out12} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
set_property OUTPUT_VALUE 2000000c00000000 [get_hw_probes jesd204c_test_bd_i/control/vio_0_probe_out12 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
commit_hw_vio [get_hw_probes {jesd204c_test_bd_i/control/vio_0_probe_out12} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
set_property OUTPUT_VALUE 2000002000000001 [get_hw_probes jesd204c_test_bd_i/control/vio_0_probe_out12 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
commit_hw_vio [get_hw_probes {jesd204c_test_bd_i/control/vio_0_probe_out12} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
set_property OUTPUT_VALUE 2000002400000009 [get_hw_probes jesd204c_test_bd_i/control/vio_0_probe_out12 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
commit_hw_vio [get_hw_probes {jesd204c_test_bd_i/control/vio_0_probe_out12} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
set_property OUTPUT_VALUE 200000280000000F [get_hw_probes jesd204c_test_bd_i/control/vio_0_probe_out12 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
commit_hw_vio [get_hw_probes {jesd204c_test_bd_i/control/vio_0_probe_out12} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
set_property OUTPUT_VALUE 2000002c00000000 [get_hw_probes jesd204c_test_bd_i/control/vio_0_probe_out12 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
commit_hw_vio [get_hw_probes {jesd204c_test_bd_i/control/vio_0_probe_out12} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
set_property OUTPUT_VALUE 2000000400000001 [get_hw_probes jesd204c_test_bd_i/control/vio_0_probe_out12 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
commit_hw_vio [get_hw_probes {jesd204c_test_bd_i/control/vio_0_probe_out12} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
 
set_property OUTPUT_VALUE 3000000800000001 [get_hw_probes jesd204c_test_bd_i/control/vio_0_probe_out12 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
commit_hw_vio [get_hw_probes {jesd204c_test_bd_i/control/vio_0_probe_out12} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
set_property OUTPUT_VALUE 3000000c00000000 [get_hw_probes jesd204c_test_bd_i/control/vio_0_probe_out12 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
commit_hw_vio [get_hw_probes {jesd204c_test_bd_i/control/vio_0_probe_out12} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
set_property OUTPUT_VALUE 3000002000000001 [get_hw_probes jesd204c_test_bd_i/control/vio_0_probe_out12 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
commit_hw_vio [get_hw_probes {jesd204c_test_bd_i/control/vio_0_probe_out12} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
set_property OUTPUT_VALUE 3000002400000009 [get_hw_probes jesd204c_test_bd_i/control/vio_0_probe_out12 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
commit_hw_vio [get_hw_probes {jesd204c_test_bd_i/control/vio_0_probe_out12} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
set_property OUTPUT_VALUE 300000280000000F [get_hw_probes jesd204c_test_bd_i/control/vio_0_probe_out12 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
commit_hw_vio [get_hw_probes {jesd204c_test_bd_i/control/vio_0_probe_out12} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
set_property OUTPUT_VALUE 3000002c00000000 [get_hw_probes jesd204c_test_bd_i/control/vio_0_probe_out12 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
commit_hw_vio [get_hw_probes {jesd204c_test_bd_i/control/vio_0_probe_out12} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
set_property OUTPUT_VALUE 3000000400000001 [get_hw_probes jesd204c_test_bd_i/control/vio_0_probe_out12 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
commit_hw_vio [get_hw_probes {jesd204c_test_bd_i/control/vio_0_probe_out12} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]

set_property OUTPUT_VALUE 4000000800000001 [get_hw_probes jesd204c_test_bd_i/control/vio_0_probe_out12 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
commit_hw_vio [get_hw_probes {jesd204c_test_bd_i/control/vio_0_probe_out12} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
set_property OUTPUT_VALUE 4000000c00000000 [get_hw_probes jesd204c_test_bd_i/control/vio_0_probe_out12 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
commit_hw_vio [get_hw_probes {jesd204c_test_bd_i/control/vio_0_probe_out12} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
set_property OUTPUT_VALUE 4000002000000001 [get_hw_probes jesd204c_test_bd_i/control/vio_0_probe_out12 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
commit_hw_vio [get_hw_probes {jesd204c_test_bd_i/control/vio_0_probe_out12} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
set_property OUTPUT_VALUE 4000002400000009 [get_hw_probes jesd204c_test_bd_i/control/vio_0_probe_out12 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
commit_hw_vio [get_hw_probes {jesd204c_test_bd_i/control/vio_0_probe_out12} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
set_property OUTPUT_VALUE 400000280000000F [get_hw_probes jesd204c_test_bd_i/control/vio_0_probe_out12 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
commit_hw_vio [get_hw_probes {jesd204c_test_bd_i/control/vio_0_probe_out12} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
set_property OUTPUT_VALUE 4000002c00000000 [get_hw_probes jesd204c_test_bd_i/control/vio_0_probe_out12 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
commit_hw_vio [get_hw_probes {jesd204c_test_bd_i/control/vio_0_probe_out12} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
set_property OUTPUT_VALUE 4000000400000001 [get_hw_probes jesd204c_test_bd_i/control/vio_0_probe_out12 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]]
commit_hw_vio [get_hw_probes {jesd204c_test_bd_i/control/vio_0_probe_out12} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku060_0] -filter {CELL_NAME=~"jesd204c_test_bd_i/control/vio_0"}]] 